### ISSUE TITLE
time to update KNOX

### ISSUE THREAD

**Issue by kaminskypavel** [timisbusy/dumpstr#4]
<i>"No Key on response from Amazon! TemporaryRedirect: Please re-send this request to the specified temporary endpoint. Continue to use the original request endpoint"</i>

I think it's because you use old version of KNOX.
look here
http://salesforce.stackexchange.com/questions/31523/problem-to-run-amazon-web-service-s3-integration-code-supported-by-salesforce

**Comment by timisbusy** [comment]
I hadn't run into that issue, but I'm happy to bump the knox version. Check out v 0.0.5
